name: Deploy CI

on:
  push:
    branches: [ main ]
  repository_dispatch:
    branches: [ master ]
    types: [ update_post ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-versions: [8.1]
      
    steps:
      - uses: actions/checkout@v3
      - name: Use PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring
      - name: Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Build
        if: steps.composer-cache.outputs.cache-hit != 'true'
        env:
          NEWT_API_KEY: ${{ secrets.NEWT_API_KEY }}
          NEWT_SERVICE_DOMAIN: ${{ secrets.NEWT_SERVICE_DOMAIN }}
        run: composer install --prefer-dist --optimize-autoloader --no-dev --no-scripts
        working-directory: ./app
      - name: Run Test
        run: vendor/bin/phpunit tests
        working-directory: ./app
  deploy-ftp:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Deploy FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ${{ secrets.FTP_PROTOCOL }}
          port: ${{ secrets.FTP_PORT }}
          server-dir: ${{ secrets.FTP_REMOTE_ROOT }}
